global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "intellialert-webhook"
  routes:
    - match:
        severity: critical
      receiver: "intellialert-webhook"
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: "intellialert-webhook"
      repeat_interval: 15m

receivers:
  - name: "intellialert-webhook"
    webhook_configs:
      - url: "http://host.docker.internal:5000/alerts"
        send_resolved: true
        http_config:
          bearer_token: "intellialert-secret-token"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "service"]
